apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 7.11.1
  nodeSets:
  - name: main-cluster
    count: 1
    config:
      node.store.allow_mmap: false